import Image from "next/image";
import type {Metadata} from "next";

// '@/' @/는 src 내의 경로를 가져온다.

/**
 * 홈 화면을 변경하세요. (변경하면서 전체 구조를 파악하세요.)
 * 페이지(/)에 대한 title을 설정하세요.
 *
 * 임의의 글자를 작성하여 주세요.
 *
 * 임의의 이미지를 다운로드 하시고 public 폴더에 넣어주세요.
 *
 * 이미지를 화면에 보이도록 해주세요.
 * (단, 이미지 크기는 200 x 200으로 합니다.)
 *
 * 크롬 네트워크 탭에서 (localhost:3000) 요청에 대한 응답을 확인하세요.
 * (html이 비어있는지 생성되어 있는지?)
 *
 * 상세 디자인과 내용은 신경쓰지 않습니다.
 * (글자 색상, 글자 내용, 이미지 종류 등)
 */
// metadata란 변수가 export 되면 metadata에 넣어줌 => 루트 Layout에서 <title>태그 달고 다는거랑 같은 거임

export const metadata = {
  title: "CISXO",
  description: "Generated by create next app",

};

export default function Home() {
  return (
    <div className="items-center justify-items-center pt-7">
      <main className="flex flex-col gap-[32px] items-center ">
        <h1>안녕하세여</h1>
        <div>
          <Image
            src="/docci.jpeg"
            alt="Next.js logo"
            width={300}
            height={200}
            priority
          />
          <button className="my-btn cursor-pointer">button</button>
        </div>
        <p>h2</p>

      </main>
    </div>
  );
}
